### ISSUE TITLE
the game crashes when i break double vertical slabs

### ISSUE THREAD

**Issue by ghost** [blay09/KleethoMod#37]
this are the mods  i have installed with version 1.16.4, forge 35,1,0
![Screenshot_3](https://user-images.githubusercontent.com/75185976/100527338-6c8b3680-31b0-11eb-9109-c56f908bcb16.png)

**Comment by BlayTheNinth** [comment]
need logs

**Comment by ghost** [comment]
[latest.log](https://github.com/blay09/KleeSlabs/files/5611328/latest.log)

**Comment by ghost** [comment]
it only happens when i break the first slab i placed (the one attached to the surfice)

**Comment by BlayTheNinth** [comment]
That log has no crash in it, latest.log is overwritten when you restart Minecraft. There's probably a separate crash log file or you have to re-create the crash and post the latest.log then before restarting Minecraft.

**Comment by ghost** [comment]
oh ok one sec

**Comment by ghost** [comment]
[latest.log](https://github.com/blay09/KleeSlabs/files/5611346/latest.log)

i tried re-creating on a wall and nothing happened, only when i tried again on a fence post (which is how it happened the first time) did it crash

**Comment by BlayTheNinth** [comment]
```
[28Nov2020 19:51:22.088] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[28Nov2020 19:51:22.088] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cjminecraft.doubleslabs.client.model.DynamicSlabBakedModel.getModelData(DynamicSlabBakedModel.java:141)
[28Nov2020 19:51:22.088] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cjminecraft.doubleslabs.client.model.VerticalSlabBakedModel.getModelData(VerticalSlabBakedModel.java:213)
[28Nov2020 19:51:22.088] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:62)
[28Nov2020 19:51:22.088] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:44)
[28Nov2020 19:51:22.089] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:102)
[28Nov2020 19:51:22.089] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:344)
[28Nov2020 19:51:22.089] [Chunk Render Task Executor #7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
```

This looks like an issue in the Double Slabs mod, or possibly the Sodium+DoubleSlabs combo.

**Comment by ghost** [comment]
yeah, i'm sorry, i tried to reproduce the issue with just klee slabs installed (which is what i should've done in the first place) and found out vertical slabs is a feature of double slabs, my bad

**Comment by ghost** [comment]
it's probably sodium+doubleslabs' fault because with just klee and doubleslabs i didn't crash
again, my bad

**Comment by ghost** [comment]
i reported incorrectly. the problem was not with KleeSlabs.
